spring:
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:file:~/sb-upload-download-file
    username: root
    password:
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect